Print more details when a behave test fails
I came across a behave test failure that looked like this:

    And all the segments are running
      Traceback (most recent call last):
        ...
        File "gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py", line 947, in impl
          raise Exception("all segments are not currently running")
      Exception: all segments are not currently running

It would have been very helpful to know which segment was not running.
This patch adds segment details to the exception messages so that such
failures are easier to debug in future.